import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, basename } from 'node:path';
import { iconFromSvg } from '../render/svg-icon.js';
import type { IconDefinition } from '../render/icons.js';
import { readZip } from './zip.js';

export interface ImportOptions {
  /** Files, folders, or zip archives. */
  inputs: string[];
  /** Regular expression a file's full path must match, for example "/64/" to take one size from a vendor set. */
  match?: RegExp;
  /** Regular expression removed from each name before it is cleaned up, for example "^(Amazon|AWS)-". */
  strip?: RegExp;
}

export interface ImportResult {
  icons: Record<string, IconDefinition>;
  skipped: { path: string; reason: string }[];
}

interface Source {
  path: string;
  read(): string;
}

function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else yield full;
  }
}

function collect(inputs: string[]): Source[] {
  const sources: Source[] = [];
  for (const input of inputs) {
    const info = statSync(input);
    if (info.isDirectory()) {
      for (const file of walk(input)) {
        if (/\.svg$/i.test(file)) sources.push({ path: file.replace(/\\/g, '/'), read: () => readFileSync(file, 'utf8') });
      }
    } else if (/\.zip$/i.test(input)) {
      for (const entry of readZip(readFileSync(input))) {
        if (/\.svg$/i.test(entry.path) && !entry.path.startsWith('__MACOSX/')) {
          sources.push({ path: `${input}!${entry.path}`.replace(/\\/g, '/'), read: () => entry.read().toString('utf8') });
        }
      }
    } else {
      sources.push({ path: input.replace(/\\/g, '/'), read: () => readFileSync(input, 'utf8') });
    }
  }
  return sources.sort((a, b) => a.path.localeCompare(b.path));
}

/** The icon name for a file: the file name without vendor prefixes, size suffix, and punctuation. */
export function iconName(path: string, strip?: RegExp): { name: string; size: number } {
  let base = basename(path).replace(/\.svg$/i, '');
  base = base.replace(/^(Arch-Category|Arch|Res)[_-]/i, '');
  const sizeMatch = /[_-](\d{2,3})$/.exec(base);
  const size = sizeMatch ? Number(sizeMatch[1]) : 0;
  if (sizeMatch) base = base.slice(0, sizeMatch.index);
  if (strip) base = base.replace(strip, '');
  const name = base
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return { name, size };
}

/** Reads SVG files and builds a set of icons keyed by clean names. Icons that cannot be made safe are skipped with a reason. */
export function importIcons(options: ImportOptions): ImportResult {
  const icons: Record<string, IconDefinition> = {};
  const sizes: Record<string, number> = {};
  const skipped: ImportResult['skipped'] = [];

  for (const source of collect(options.inputs)) {
    if (options.match && !options.match.test(source.path)) continue;
    const { name, size } = iconName(source.path, options.strip);
    if (!name) {
      skipped.push({ path: source.path, reason: 'The file name has nothing left after cleaning.' });
      continue;
    }
    if (name in icons && size <= sizes[name]!) {
      skipped.push({ path: source.path, reason: `Another file already provides "${name}".` });
      continue;
    }
    try {
      icons[name] = iconFromSvg(source.read());
      sizes[name] = size;
    } catch (cause) {
      skipped.push({ path: source.path, reason: cause instanceof Error ? cause.message : String(cause) });
    }
  }
  return { icons, skipped };
}

/** Source for a module that exports the icons. */
export function renderModule(prefix: string, icons: Record<string, IconDefinition>): string {
  const ident = prefix.replace(/[^a-zA-Z0-9_$]/g, '_').replace(/^(\d)/, '_$1') || 'icons';
  const entries = Object.keys(icons)
    .sort()
    .map((name) => `  ${JSON.stringify(name)}: ${JSON.stringify(icons[name])},`);
  return [
    '// Generated by `diagrammar icons import`. Edit the source files and run it again instead of changing this file.',
    "import type { IconDefinition } from 'diagrammar/render';",
    '',
    `export const ${ident}: Record<string, IconDefinition> = {`,
    ...entries,
    '};',
    '',
    `export default ${ident};`,
    '',
  ].join('\n');
}
