// Builds src/logos/index.ts from the simple-icons dev dependency (CC0-1.0).
// Run with: npm run logos
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkgDir = join(root, 'node_modules', 'simple-icons');
const pkg = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8')) as { version: string };
const data = JSON.parse(readFileSync(join(pkgDir, 'data', 'simple-icons.json'), 'utf8')) as { title: string; slug: string; hex: string }[];

/** Name used in diagrams, mapped to the Simple Icons slug. */
const LOGOS: Record<string, string> = {
  git: 'git',
  github: 'github',
  docker: 'docker',
  kubernetes: 'kubernetes',
  terraform: 'terraform',
  linux: 'linux',
  nginx: 'nginx',
  cloudflare: 'cloudflare',
  vercel: 'vercel',
  postgresql: 'postgresql',
  mysql: 'mysql',
  mongodb: 'mongodb',
  redis: 'redis',
  supabase: 'supabase',
  rabbitmq: 'rabbitmq',
  kafka: 'apachekafka',
  graphql: 'graphql',
  react: 'react',
  nextjs: 'nextdotjs',
  typescript: 'typescript',
  nodejs: 'nodedotjs',
  python: 'python',
  grafana: 'grafana',
  prometheus: 'prometheus',
  stripe: 'stripe',
  snowflake: 'snowflake',
  databricks: 'databricks',
  airflow: 'apacheairflow',
  spark: 'apachespark',
  elasticsearch: 'elasticsearch',
  clickhouse: 'clickhouse',
  duckdb: 'duckdb',
  minio: 'minio',
  trino: 'trino',
  airbyte: 'airbyte',
  datadog: 'datadog',
  sentry: 'sentry',
  'github-actions': 'githubactions',
  gitlab: 'gitlab',
  hashicorp: 'hashicorp',
  jira: 'jira',
  go: 'go',
  rust: 'rust',
};

function luminance(hex: string): number {
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255) as [number, number, number];
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

const lines: string[] = [];
for (const name of Object.keys(LOGOS).sort()) {
  const slug = LOGOS[name]!;
  const meta = data.find((d) => d.slug === slug);
  if (!meta) throw new Error(`simple-icons has no "${slug}".`);
  const svg = readFileSync(join(pkgDir, 'icons', `${slug}.svg`), 'utf8');
  const d = /<path d="([^"]+)"/.exec(svg)?.[1];
  const box = /viewBox="([^"]+)"/.exec(svg)?.[1];
  if (!d || !box) throw new Error(`Could not read ${slug}.svg.`);
  // Near-black and near-white brands would vanish on one of the two themes, so they follow the text color.
  const l = luminance(meta.hex);
  const fill = l < 0.1 || l > 0.9 ? 'currentColor' : `#${meta.hex.toLowerCase()}`;
  const body = `<path fill="${fill}" d="${d}"/>`;
  lines.push(`  ${JSON.stringify(name)}: { body: ${JSON.stringify(body)}, viewBox: ${JSON.stringify(box)}, color: true }, // ${meta.title}`);
}

const out = `// Generated by scripts/logos.ts from simple-icons ${pkg.version} (CC0-1.0). Do not edit by hand.
//
// The artwork is public domain, but the logos are trademarks of their owners. Use them to refer
// to those products, and follow each owner's brand guidelines. See https://simpleicons.org.
import type { IconDefinition } from '../render/icons.js';

/** Register under a prefix, then use "logo:name": registerIconPack('logo', logos). */
export const logos: Record<string, IconDefinition> = {
${lines.join('\n')}
};

export default logos;
`;
mkdirSync(join(root, 'src', 'logos'), { recursive: true });
writeFileSync(join(root, 'src', 'logos', 'index.ts'), out);
console.log(`Wrote ${lines.length} logos.`);
